import { ChangeEvent, useCallback, useEffect, useRef, useState } from 'react'

import { useCollection } from '@audius/common/api'
import { imageBlank } from '@audius/common/assets'
import { SquareSizes } from '@audius/common/models'
import { getErrorMessage } from '@audius/common/utils'
import { Button, IconPencil, Image } from '@audius/harmony'
import cn from 'classnames'
import { pick } from 'lodash'
import { Link } from 'react-router'

import { useCollectionCoverArt } from 'hooks/useCollectionCoverArt'
import { resizeImage } from 'utils/imageProcessingUtil'

import styles from './CollectionHeader.module.css'
import { usePlaylistEditMode } from './edit-mode/PlaylistEditModeContext'

const messages = {
  addArtwork: 'Add Artwork',
  changeArtwork: 'Change Artwork',
  removeArtwork: 'Remove Artwork',
  coverArtAltText: 'Collection Cover Art'
}

type ArtworkProps = {
  collectionId: number
  isOwner: boolean
}

export const Artwork = (props: ArtworkProps) => {
  const { collectionId, isOwner } = props

  const { data: partialCollection } = useCollection(collectionId, {
    select: (collection) =>
      pick(collection, 'is_image_autogenerated', 'permalink')
  })
  const { is_image_autogenerated, permalink } = partialCollection ?? {}

  const { imageUrl: image } = useCollectionCoverArt({
    collectionId,
    size: SquareSizes.SIZE_1000_BY_1000
  })

  const hasImage = image && image !== imageBlank

  const editMode = usePlaylistEditMode()
  const isEditingThis =
    editMode.isEditMode && editMode.collectionId === collectionId

  const fileInputRef = useRef<HTMLInputElement>(null)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    if (!isEditingThis) setError(null)
  }, [isEditingThis])

  const handleFileChange = useCallback(
    async (e: ChangeEvent<HTMLInputElement>) => {
      const file = e.target.files?.[0]
      e.target.value = ''
      if (!file) return
      try {
        const resized = await resizeImage(file)
        // @ts-ignore writing to read-only property; matches ArtworkField pattern
        resized.name = file.name
        const url = URL.createObjectURL(resized)
        editMode.setField('artwork', { url, file: resized, source: 'inline' })
        setError(null)
      } catch (err) {
        setError(getErrorMessage(err))
      }
    },
    [editMode]
  )

  const draftArtwork = editMode.draft.artwork
  const displaySrc = isEditingThis && draftArtwork ? draftArtwork.url : image

  return (
    <Image
      className={cn(styles.coverArtWrapper, styles.coverArt)}
      alt={messages.coverArtAltText}
      src={displaySrc}
    >
      {isOwner ? (
        <span className={styles.imageEditButtonWrapper}>
          {isEditingThis ? (
            <>
              <Button
                variant='tertiary'
                iconLeft={IconPencil}
                onClick={() => fileInputRef.current?.click()}
              >
                {messages.changeArtwork}
              </Button>
              <input
                ref={fileInputRef}
                type='file'
                accept='image/*'
                style={{ display: 'none' }}
                onChange={handleFileChange}
                aria-label={messages.changeArtwork}
                aria-invalid={!!error}
              />
            </>
          ) : (
            <Button variant='tertiary' iconLeft={IconPencil} asChild>
              <Link
                to={{
                  pathname: `${permalink}/edit`,
                  search:
                    hasImage && !is_image_autogenerated
                      ? undefined
                      : '?focus=artwork'
                }}
              >
                {hasImage && !is_image_autogenerated
                  ? messages.removeArtwork
                  : hasImage
                    ? messages.changeArtwork
                    : messages.addArtwork}
              </Link>
            </Button>
          )}
        </span>
      ) : null}
    </Image>
  )
}
