import { randomBytes } from 'crypto'

import chalk from 'chalk'
import { Command, Option } from '@commander-js/extra-typings'

import { getHedgehog, initializeAudiusSdk, parseBoolean } from '../utils.js'
import { LocalStorage } from 'node-localstorage'
import { decodeHashId } from '@audius/sdk'
import { outputFormatOption } from '../common-options.js'
const localStorage = new LocalStorage('./local-storage')

export const createUserCommand = new Command('create')
  .description('Create a new user')
  .argument(
    '[handle]',
    'The handle for the new user (chosen randomly if not specified)'
  )
  .option(
    '-p, --password <password>',
    'The password for the new user',
    'password'
  )
  .option(
    '-e, --email <email>',
    'The email for the new user (chosen randomly if not specified)'
  )
  .addOption(outputFormatOption)
  .action(async (requestedHandle, options) => {
    const audiusSdk = await initializeAudiusSdk()

    const rand = randomBytes(2).toString('hex').padStart(4, '0').toUpperCase()
    const handle = requestedHandle || `user${rand}`

    const { email = `audius-cmd+${handle}@audius.co`, password = 'password' } =
      options

    const hedgehog = getHedgehog()
    // Create identity service user
    const res = await hedgehog.signUp({ username: email, password })

    const userRes = await audiusSdk.users.createUser({
      metadata: {
        bio: `account generated by audius-cmd ${rand}`,
        handle,
        location: `location${rand}`,
        name: `name ${rand}`,
        wallet: res.getAddressString()
      }
    })
    const { userId } = userRes

    const entropy = localStorage.getItem('hedgehog-entropy-key')

    if (options.output === 'json') {
      console.log(JSON.stringify(userRes))
    } else {
      console.log(chalk.green('Successfully created user!'))
      console.log(chalk.yellow.bold('Handle:   '), handle)
      console.log(chalk.yellow.bold('User ID:  '), userId)
      console.log(chalk.yellow.bold('User ID #:'), decodeHashId(userId!))
      console.log(chalk.yellow.bold('Email:    '), email)
      console.log(chalk.yellow.bold('Password: '), password)
      console.log(chalk.yellow.bold('Entropy:  '), entropy)
      console.log(
        chalk.yellow.bold('Wallet:   '),
        hedgehog.getWallet()?.getAddressString()
      )
    }

    localStorage.setItem(`handle-${handle}`, entropy!)
  })
